name: Generate Table Of Contents
# Define when to run job here
on: [push, pull_request]

jobs:
  example_job:
    runs-on: ubuntu-latest
    name: Runing Github Downloader
    steps:
    - uses: actions/checkout@v2
    - uses: MarketingPip/Table-of-Contents-Generator@main
